### ISSUE TITLE
Feature Request: Truncate string on overflow and add full text as toltip

### ISSUE THREAD

**Issue by sravan-s** [Saulis/iron-data-table#119]
Would like to have an inbuilt property to handle overflown text, as in here: 
![overflow](https://cloud.githubusercontent.com/assets/11382805/16940529/2f273cc6-4da8-11e6-86a8-5afa892eed9c.png)

I have implemented a fix in my branch: [feature/cell-overflow-ellipsis](https://github.com/Saulis/iron-data-table/compare/master...sravan-s:feature/cell-overflow-ellipsis?expand=1). The results are something like this.
![ellipsis](https://cloud.githubusercontent.com/assets/11382805/16940558/6904d23c-4da8-11e6-93ab-42c8d219a0fc.png)

If you guys think this is a valid request, I'll raise a pull request.

**Comment by Saulis** [comment]
Hi!

Interesting suggestion – I have a few questions about the implementation. Can the ellipsis be set directly to `<data-table-cell>` so that an extra `<span>` isn't needed? If yes, I think this could be set as a default style so that a property `ellipsis` is not needed.

Also, I'd leave out setting any values to the `title`; I'm worried making assumptions that `innerHTML` contains the correct value (it might have HTML).

**Comment by sravan-s** [comment]
@Saulis I'll try out your suggestion on putting style directly on data-table-cell.
I really need that text on hover. Any ideas for implementing it? Actually, I put the 'span' inside data-table-cell  to implement that text over hover.

**Comment by sravan-s** [comment]
Well, I checked it. But ellipsis seems to have some problems with **display: flex.** We are using dispaly: flex on **data-table-cell**. Wrapping text inside  a container seems to help.
