### ISSUE TITLE
Moving paper-input inside iron-data-table to its own sub-element causes row-detail to collapse when focused

### ISSUE THREAD

**Issue by maria-le** [Saulis/iron-data-table#125]
[See this question on StackOverflow](http://stackoverflow.com/q/38693018/1640892).

**Comment by Saulis** [comment]
Hi!

When a row is clicked, `localTarget` for the click is checked for focus. If the target is focusable, then the row will not be selected/expanded. In your case, `localTarget` doesn't penetrate the shadow root of an element and therefore it doesn't know that `paper-input` (or the input inside that) is focused. So, `localTarget` returns `row-detail` element which is not focused.

I've tried also using `rootTarget` for checking the focused element, but that doesn't work with components like `paper-checkbox` which doesn't have an input inside at all.

So, as I've answered in the Stack, the correct way to work around this issue is to make your wrapping custom element focusable. For example, by setting `tabindex="0"` to it.
