### ISSUE TITLE
Using row item as param for function call

### ISSUE THREAD

**Issue by hankphung** [Saulis/iron-data-table#137]
I pass item as param like this and got error item not defined
``` <iron-data-table items="[[data]]" multiSelection pageSize="[[perpage]]" id="campainTable" >

``````
      <data-table-column name="Title">
        <template>[[item.title]]</template>
      </data-table-column>

      <data-table-column name="Price">
        <template>[[item.price]]</template>
      </data-table-column>

      <data-table-column name="Action">

       <template>

         <paper-button onclick="_edit(item)">   E </paper-button>

       </template>

      </data-table-column>

  </iron-data-table>```
``````

**Comment by web-padawan** [comment]
First, you should use `on-tap` (Polymer listeners) instead of `onclick` (plain JS).
And another thing: you cannot pass item like this when using Polymer listeners, so the correct syntax is:

``` html
<paper-button on-tap="_onItemTap">   E </paper-button>
```

Then, pay attention to `e.model` inside of the listener:

``` js
  _onItemTap: function (e) {
    console.log('Title: ' + e.model.item.title);
  }
```

The same approach works for `dom-repeat` templates as well.

**Comment by hankphung** [comment]
@web-padawan Thank you, it work now. 
This gonna help when put in the element demos.
