### ISSUE TITLE
lazyloading - useful sooner than later

### ISSUE THREAD

**Issue by ktiedt** [Saulis/iron-data-table#15]
Of the missing features this is the one most likely to block our adoption across the board for our projects.

If you have plans or ideas on how you wanted to achieve this, happy to give an attempt at implementing that. Just don't want to step on existing plans or conflict w/potential existing designs plans.

**Comment by Saulis** [comment]
Hi!

I actually did a proof-of-concept on lazy loading on the very earliest versions I had implemented (actually it was [commit number 2](https://github.com/Saulis/iron-data-table/commit/bd091b353bd41519fb69b75600b02213f84826ab) in this repo :smile: ), but since it was a prototype and I wasn't sure how important this feature was for people I decided to move the implementation for later. 

So, thanks to your feedback, I now know we should raise the importance on the lazy loading.

I'd love to get any help possible on this, just need to get my thoughts together first, so bare with me :smile: 

Here's a brief summary of the basic idea I have in mind:

Since `iron-list` itself doesn't have support for lazy loading, we need to give an dummy array of empty values with the length of the remote data source to be able to have a correctly sized scroll bar. While loading data, we will fill in the missing values in the array. I verified this to work on my prototype, but I haven't yet performance tested this concept thoroughly with large datasets.

I'd say the main task here is to implement a system that detects when and which rows should be requested and filled in the items array of the `iron-list`. `scroll` event fired from the list is most probably the trigger we will use. In my prototype I used `firstVisibleIndex` from `iron-list` to detect at which point we are, but it's a pretty heavy operation to do on every `scroll` event, so I'm now thinking about something else: probably an array of pre-calculated `scrollTop` positions which are in relation with pages on the data source.

``` js
// given the average item height is 50px and page size is 20 items:
var bookkeeping = [{position: 0, loaded: false}, //page 0
    {position: 1000, loaded: false}, //page 1
    {position: 2000, loaded: false}, //page 2
...]

//in scroll event handler we would then see on which page we are at:
for (var i = 0; i < bookkeeping.length; i++) {
  if (scrollTop >= bookkeeping[i] && scrollTop < bookkeeping[i+1]) {
    // make sure bookkeeping[i-1], bookkeeping[i] and bookkeeping[i+1] are loaded, if not
   // fetch them.
  }
}
```

This _should_ work nicely as long as the item heights are constant. For variable row heights we would probably need to do some adjustments on the book keeping positions, but I wouldn't worry about that yet because variable row heights are problematic in any implementation.

The API would probably resemble quite much the `vaadin-grid` one, except that we would use pages instead of row indexes.

Things to do (might be a bit vague at this point still):
1. Would be useful information to performance test the current implementation with a static dataset of 200 000 items and less. If there are no problems with a static array, then lazy loading should work just fine.
2. Figure out a reliable way for calculating the item height we should use to determine the page height in pixels. Maybe use the `_physicalSizes` array inside `iron-list` ?
3. Implement a book keeping system for the caching and data fetching.
4. Hook lazy loading up to `iron-list`, filtering, sorting and grouping parameters should be sent to the remote data source function.
5. Wrap static `items` arrays into function data sources and use the current built-in filtering, sorting and grouping functionality inside.
6. Add a nice loading spinner :smile: 

How does this sound to you overall? Did I miss something? 

Update: see branch https://github.com/Saulis/iron-data-table/compare/feature/lazy-loading I've added a basic observer that will keep track on which page we are currently on. The implementation is actually simpler than I described in the code snippet above.

**Comment by Saulis** [comment]
Added a new commit to the branch, now basic data loading is implemented using the static array in `items`. You can also try out overriding the `dataSource` function and setting a `size` value manually if you want to try out with a real remote data source.

**Comment by Saulis** [comment]
It's starting to come together, needs to be tested still with some real remote data. Multi-selection still needs to be figured out, and the loading spinner. Thinking to drop the row grouping feature at this point until a better data structure has been thought out.

**Comment by Saulis** [comment]
I'm going to release the current version in `alpha4`, let's keep tweaking it if needed.

**Comment by ktiedt** [comment]
Awesome, cant wait to try it out.
