### ISSUE TITLE
Some rows are not rendered when using iron-list 1.2.x

### ISSUE THREAD

**Issue by Saulis** [Saulis/iron-data-table#4]
![image](https://cloud.githubusercontent.com/assets/1039468/13058756/f7fe3d92-d42d-11e5-8ddc-e206c670d27b.png)

Tested on `<iron-list>` 1.2.4

**Comment by ktiedt** [comment]
Not entirely sure what the cause is here, but I do have some information that may prove useful.

Attempting to debug this, I see that data-table-cell's _render methods get called roughly 3 times on page load. The first go around, The template data can be seen to contain the proper data templates for indices 1 and 2, but subsequent calls (the 2nd and 3rd times) the templated data vanishes.

I've had a long day and thats as much as I could glean from this so far. Maybe it will inspire an idea for someone else to figure this out, if I dont get back to it tomorrow ;)

**Comment by Saulis** [comment]
Thanks a lot for looking into this, I'm not sure if I have time to dig deeply into it myself before next week.

After a quick glance, with `?dom=shadow`, first three cells of the first column don't get rendered: weirdly, `columns[0]._templateInstances` items 1-3 (0 is the header) don't have any `item` defined. Turns out that the `_bind` method for these three cells isn't called at all for some reason.

With Shady DOM, though, it renders differently. And also the `_templateInstances` seem to have items in place correctly. 

Regarding `data-table-cell` it still needs some refactoring: the problem is that it needs multiple properties in order to function, `column`, `template` and the `bind` data - and currently they're all bound separately and possibly in random order. 

Update: the `[[index]]` seems to be working just fine outside the `dom-repeat` element in the `iron-list` item template, which generates the `data-table-cell` elements for each row.

Update 2: Seems like the root cause for problems is different for Shady and Shadow DOM. Removing the `dom-repeat` element fixes Shadow DOM but doesn't help with Shady.

**Comment by Saulis** [comment]
Reverting this change: https://github.com/PolymerElements/iron-list/commit/c0e27e52ee93dcd93d33590b569bd17c5c504005#diff-b97995700c5da5fa638d0324b5f3f861L765 seems to fix the issue on Shady DOM, Shadow DOM still a bit wonky.
