### ISSUE TITLE
dataSource function invoked twice

### ISSUE THREAD

**Issue by gazal-k** [Saulis/iron-data-table#62]
When using the dataSource property, noticed that function is getting triggered twice for each page. Also noticed the same thing on the demo page, https://saulis.github.io/iron-data-table/demo/.

Couldn't quite figure out what the reason is. I saw that the `_loadPage` function is debounced, but it still gets triggered an extra time unnecessarily.

**Comment by Saulis** [comment]
Hi!

Can't see this happening on each page load, but only on in the beginning when pages `0` and `1` are being loaded. That seems to be happening because of the `debouce` in `_resetData` which clears the cache – small race condition there together with the `_loadPage` function. Decreasing debounce on `_resetData` seems to help.

**Comment by gazal-k** [comment]
Did u already fix it? Should I help?

**Comment by Saulis** [comment]
I can fix it if you can verify the issue was concerning only the initial page load?

**Comment by gazal-k** [comment]
Yes, confirmed.
