### ISSUE TITLE
Provide way for filter by multiple items

### ISSUE THREAD

**Issue by dpoluyanov** [Saulis/iron-data-table#73]
Currently, iron-data-table supports filtering by one value. But sometimes we need way for filter by list of options, for example: we have list of statuses, like 'Open', 'Closed', 'In Progress', etc, and only 'Open' and 'Closed' should be showed in datable.

**Comment by Saulis** [comment]
Hi there!

This is already doable if you just place a custom component that supports multi-selection in the header. `vaadin-combo-box` I've used in one of the [filtering examples](http://saulis.github.io/iron-data-table/demo/filtering.html) is pretty neat, it doesn't have multi-selection yet, but they have it on their roadmap.

`iron-data-table` currently depends on `paper-input` which is used as a default filter template implementation, but I'm not planning on adding any other default input templates with some third-party components.

I'm going to close this issue for now, since I believe filtering with multiple items is doable currently, please feel free to comment or reopen the issue if there is something that prevents from succeeding.

**Comment by dpoluyanov** [comment]
Currently, items filtered by next code
 `array-datasource.js`:

``` javascript
if (!filter[i].filter) {
  continue;
} else if (!value || value.toString().toLowerCase().indexOf(filter[i].filter.toString().toLowerCase()) === -1) {
  return false;
}
```

It's right?
That mean, that user can't filter one item property by several values simultaneously.
For example, in Polymer `dom-repeat` template we can filter items by function, like this:

``` html
<template id="domRepeatTemplate" is="dom-repeat" filter="isHidden" observe="status">
   <tr>
      <td>[[item.name]]</td>
      <td>[[item.status]]</td>
   </tr>
</template>

...

<script>
properties: {
   statusesFilter: {
      type: Array,
      notify: true,
      value: ['Open', 'Closed'],
      observer: '_statusesFilterChanged'
   }
},

function: isHidden(item) {
   var visible = false;

   for (var i = 0; i < statusesFilter.length; i++) {
      visible = visible || item.status.toString().toLowerCase().indexOf(statusesFilter[i].toString().toLowerCase()) !== -1;
   }
   return !visible;
},

_statusesFilterChanged: function() {
   this.$.domRepeatTemplate.render();
}
</script>

```

May be thing, like this is not in current plan for iron-data-table element, but it can be a great feature in future releases.
